name: Add issues and PRs to project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, synchronize]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue or PR to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/handong-app/projects/5
          github-token: ${{ secrets.PROJECT_PAT }}
