name: Auto Assign Reviewer

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    paths:
      - "src/**"
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write
  contents: read

jobs:
  assign-reviewer:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/actions/auto-assign-reviewer
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key and agent (for act)
        if: env.ACT
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.REPO_PRIVATECMS_PRIVATE_KEY }}" | tr -d '\r' | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone secrets-repo manually (for act)
        if: env.ACT
        working-directory: ${{ github.workspace }}
        run: |
          git clone --depth=1 --filter=blob:none --sparse git@github.com:handong-app/CMS-private.git secrets-repo
          cd secrets-repo
          git sparse-checkout init --cone
          git sparse-checkout set auto-assign-reviewer

      - name: Checkout Secrets Repo
        if: ${{ !env.ACT }}
        uses: actions/checkout@v4
        with:
          repository: handong-app/CMS-private
          ref: main
          ssh-key: ${{ secrets.REPO_PRIVATECMS_PRIVATE_KEY }}
          path: secrets-repo
          sparse-checkout: |
            auto-assign-reviewer

      - name: Copy reviewers.json
        working-directory: ${{ github.workspace }}
        run: |
          cp secrets-repo/auto-assign-reviewer/reviewers.json .github/actions/auto-assign-reviewer/reviewers.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run custom reviewer assigner
        uses: ./.github/actions/auto-assign-reviewer
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-token: ${{ secrets.DISCORD_TOKEN }}

      - name: Cleanup secrets-repo
        if: always()
        working-directory: ${{ github.workspace }}
        run: |
          rm -rf secrets-repo

      - name: Cleanup reviewers.json
        if: always()
        working-directory: ${{ github.workspace }}
        run: |
          rm -f .github/actions/auto-assign-reviewer/reviewers.json
