name: Validate Auto Assign Reviewer Action Build

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
    paths:
      - ".github/actions/auto-assign-reviewer/**"
  push:
    branches:
      - main
    paths:
      - ".github/actions/auto-assign-reviewer/**"

jobs:
  check-dist:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false || github.event_name == 'push'
    defaults:
      run:
        working-directory: .github/actions/auto-assign-reviewer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Rebuild action
        run: npm run build

      - name: Check if dist is up-to-date
        run: |
          git diff --exit-code dist || {
            echo "❌ dist/ is not up to date. Please run 'npm run build' and commit the result."
            exit 1
          }
